#!/bin/bash

source /opt/ros/noetic/setup.bash
echo "ROS_IP: $(hostname -i)" > $ROS_WORKSPACE/src/ur3_moveit/config/params.yaml
cd $ROS_WORKSPACE
catkin_make -DCATKIN_WHITELIST_PACKAGES="moveit_msgs;ros_tcp_endpoint;ur3_moveit;robotiq_2f_140_gripper_visualization;ur_description;ur_gazebo"